### ISSUE TITLE
Customized Styler

### ISSUE THREAD

**Issue by rossdrucker** [lorenzwalthert/precommit#298]
I'm trying to create a precommit hook with a slightly-altered version of the tidyverse style guide, but am having trouble getting it to execute. The main difference between the style guide I'm following and the tidyverse style guide is using the `=` assignment operator instead of `<-`.  I've configured the changes I'd like to include using the `styler` package, but can't seem to get it to work with the `styler` precommit hook. Happy to provide any code as necessary.

Thanks in advance!

**Comment by lorenzwalthert** [comment]
Hi @rossdrucker 😀 
You'll need what's outlined in the [hook description](https://lorenzwalthert.github.io/precommit/articles/available-hooks.html#style-files), that is, an R package that exports a style guide. This package needs to be locally installed at the time you call the hook, or if you use a fairly recent version of the hooks (>= 0.1.3.9130), you'll need to also add a reference to your package (GitHub or CRAN) in `additional_dependencies` in the `.pre-commit-config.yaml` such that `renv::install()` understands it, e.g. [`lorenzwalthert/oneliner`](https://github.com/lorenzwalthert/oneliner) points to my styler fork, so I could: 
```
  id: style-files
  args: [--style_pkg=oneliner, --style_fun=one_line_style]
  additional_dependencies:
  -    lorenzwalthert/oneliner
```
