### ISSUE TITLE
Style Quarto docs

### ISSUE THREAD

**Issue by RoyalTS** [lorenzwalthert/precommit#392]
As soon as the next `styler` release is cut and [https://github.com/r-lib/styler/issues/913](this) goes live, add `.qmd` files to apply the `style-files` hook to.

**Comment by lorenzwalthert** [comment]
You can already do this by overriding `files` and `additional_dependencies: - r-lib/styler` if you want.

**Comment by lorenzwalthert** [comment]
We are not bound by CRAN version of {styler}, so we could already implement that now. 
`files` just has to be a regex that matches quarto docs, see https://github.com/lorenzwalthert/precommit/blob/main/.pre-commit-hooks.yaml#L21

**Comment by RoyalTS** [comment]
You're saying a `.pre-commit-config.yaml` that includes

```
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.3.2
  hooks:
  - id: style-files
    args: [--style_pkg=styler, --style_fun=tidyverse_style]
    additional_dependencies:
    - r-lib/styler
    files: '(\.[rR]profile|\.R|\.Rmd|\.Rnw|\.r|\.rmd|\.rnw|\.qmd)$'
    exclude: 'renv/activate\.R'
```

should do the trick?
