### ISSUE TITLE
Problem installing git2r via pre-commit Github Action

### ISSUE THREAD

**Issue by thefabnab** [lorenzwalthert/precommit#496]
**Before filing a bug**

- [x] I have installed the latest dev version of {precommit} with `remotes::install_github('lorenzwalthert/precommit')`
- [x] I have installed the latest hook revisions (update with `precommit::autoupdate()`)
- [x] I have installed the latest release of the upstream Python framework pre-comit as described under the [update instructions](https://lorenzwalthert.github.io/precommit/dev/articles/precommit.html#update).

**Describe the bug**
I have a repository with both Python and R code. I'm testing out the `parsable-R` action and finding that while I can run it locally when I try and execute this hook as a github action via `pre-commit/action@v3.0.0` I'm seeing the following error:

```
    - Installing git2r ...                          FAILED
    Traceback (most recent calls last):
    14: renv::restore()
    13: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
    12: renv_install_impl(records)
    11: renv_install_staged(records)
    10: renv_install_default(records)
     9: handler(package, renv_install_package(record))
     8: renv_install_package(record)
     7: withCallingHandlers(renv_install_package_impl(record), error = function(e) writef("FAILED"))
     6: renv_install_package_impl(record)
     5: withCallingHandlers(if (isbin) renv_install_test(package), error = function(err) unlink(installpath, 
            recursive = TRUE))
     4: renv_install_test(package)
     3: renv_system_exec(command = R(), args = c("--vanilla", "-s", "-f", 
            renv_shell_path(script)), action = sprintf("testing if '%s' can be loaded", 
            package))
     2: abort(sprintf("error %s [error code %i]", action, status), body = renv_system_exec_details(command, 
            args, output))
     1: stop(fallback)
stderr:
    Warning message:
    renv took longer than expected (20 seconds) to activate the sandbox.
    
    The sandbox can be disabled by setting:
    
        RENV_CONFIG_SANDBOX_ENABLED = FALSE
    
    within an appropriate start-up .Renviron file.
    
    See `?renv::config` for more details. 
    /opt/R/4.2.1/lib/R/bin/R --vanilla -s -f '/tmp/RtmpHrbPW9/renv-install-172d5819cf03'
    ================================================================================
    
    Error: package or namespace load failed for ‘git2r’ in dyn.load(file, DLLpath = DLLpath, ...):
     unable to load shared object '/home/runner/.cache/pre-commit/report0v4sfl/renv-default/renv/staging/1/git2r/libs/git2r.so':
      libgit2.so.1.1: cannot open shared object file: No such file or directory
    Execution halted
    
    Error: error testing if 'git2r' can be loaded [error code 1]
    Execution halted
Check the log at /home/runner/.cache/pre-commit/pre-commit.log
Error: Process completed with exit code 3.
```

**To Reproduce**
Hopefully this could help you reproduce the issue... here are the contents of my `.pre-commit-config.yaml`:
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9015
    hooks:
      - id: parsable-R
```

as well as the Pre-commit file:
```
name: Pre-Commit

on:
  pull_request:
    branches:
      - main
    tags:
      - v**
jobs:
  pre-commit:
    name: Run Repo pre-commit checks
    runs-on: ubuntu-22.04
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'

      - name: Setup R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Run pre-commits
        uses: pre-commit/action@v3.0.0
```

These are all pretty run of the mill, nothing fancy.

**Expected behavior**
What I'd like to have happen is to have this pre-commit hook run as expected via Github Action like it does when I run this locally:

```
check python ast.........................................................Passed
check for case conflicts.................................................Passed
check yaml...............................................................Passed
check json...........................................(no files to check)Skipped
fix end of files.........................................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
detect private key.......................................................Passed
check for added large files..............................................Passed
black....................................................................Passed
isort....................................................................Passed
docformatter.............................................................Passed
autoflake................................................................Passed
parsable-R...............................................................Passed
```

**Additional context**

- My operating system is: 
- [ ] My project uses {renv}.
- [ ] the output of `packageVersion('renv')`

**Comment by lorenzwalthert** [comment]
The same problem ocurred with [pre-commit.ci](https://results.pre-commit.ci/run/github/186313720/1690479615.t0B77j5dS1Gu3gO0Li4t7w) recently, I think you have to update R to 4.3.1 in your GitHub Action file to avoid building {git2r} from source.

**Comment by thefabnab** [comment]
Thanks, I'll try this out and report back.

**Comment by thefabnab** [comment]
@lorenzwalthert 

Hmmm looks like I'm still seeing the issue. I upgraded base R version via the setup-r action:

```
 - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'
```

Before it was `r-version: '4.2.1'`. Here's a copy of the same error observed:

```
    Error: package or namespace load failed for ‘git2r’ in dyn.load(file, DLLpath = DLLpath, ...):
     unable to load shared object '/home/runner/.cache/pre-commit/repotdmq00ww/renv-default/renv/staging/1/git2r/libs/git2r.so':
      libgit2.so.1.1: cannot open shared object file: No such file or directory
    Execution halted
    
    Error: error testing if 'git2r' can be loaded [error code 1]
    Execution halted
```

**Comment by thefabnab** [comment]
@lorenzwalthert update

From this thread: https://github.com/ropensci/git2r/issues/378 I added a step installing `libgit2-dev` via:
```
- name: Install Dependencies
        run: sudo apt-get install -y libgit2-dev
```
and now the build proceeds as expected the first time it's build **however**, when I run the action a second time with another commit I'm seeing the following:

```
/usr/bin/tar -xf /home/runner/work/_temp/e58220e2-d41a-45d9-9f1a-e2995ebf9737/cache.tzst -P -C /home/runner/work/R-D/R-D --use-compress-program unzstd
Cache restored successfully
Cache restored from key: pre-commit-3|/opt/hostedtoolcache/Python/3.9.17/x64|c460a14a211d3a872d8ab2954c63b3a50b7bebef1527043d1335eb2cf8442f51
Run pre-commit run --show-diff-on-failure --color=always --all-files
check python ast.........................................................Passed
check for case conflicts.................................................Passed
check yaml...............................................................Passed
check json...............................................................Passed
fix end of files.........................................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
detect private key.......................................................Passed
check for added large files..............................................Passed
black....................................................................Passed
isort....................................................................Passed
docformatter.............................................................Passed
autoflake................................................................Passed
parsable-R...............................................................Failed
- hook id: parsable-R
- exit code: 1

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘R.cache’
Calls: lapply ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

Seems like `R.cache` isn't showing up in the R virtual environment instantiated.

Here's what the `actions/cache@v3` action is doing:

```
Run actions/cache@v3
  with:
    path: ~/.cache/pre-commit
    key: pre-commit-3|/opt/hostedtoolcache/Python/3.9.17/x64|c460a14a211d3a872d8ab2954c63b3a50b7bebef1527043d1335eb2cf8442f51
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.17/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.17/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.17/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.17/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
    R_LIB_FOR_PAK: /opt/R/4.3.1/lib/R/site-library
```
